### ISSUE TITLE
Needs restructuring.

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Output-Bird-Habitat#3]

**Comment by rmscheller** [comment]
Bruce,
I cleaned things up considerably and it is now compiling correctly.  It needs to be tested whether it is compatible with the Biomass Library - it should NOT require NECN.  Should work with Biomass Succession.  The example should use Biomass Succession, not NECN.

**Comment by bmarron18** [comment]
Was able to match BiomassSuccession_s2e3 as an example for testing, to successfully build  Landis.Extension.Output.BirdHabitat.dll, to successfully build the installer, and to successfully install the extension. Output Bird Habitat did not, however, pass QAQC even after three intermediate fixes (described in PWL74b_QAQC&RepoStd_OutputBirdHabitat_20170612.txt). The final exception/error may suggest that the extension is not compatible with Biomass Library,

Loading Output Bird Habitat extension ...
Cohorts are empty.  Please double-check that this extension is compatible with your chosen succession extension.

**Comment by rmscheller** [comment]
Bruce, a small typo - think I got it now.

**Comment by bmarron18** [comment]
Great job finding the typo and yes, that certainly seems to get the extension to the next stage but there are still some problems. 

With  Line 48 "output_BirdHabitat.txt" uncommented we get,
Running Output Bird Habitat ...
The Climate parameter pdsi is listed for model PIWA but is not included under ClimateVariables.

With Line 48 and Line 55 of "output_BirdHabitat.txt" commented out we get,
Loading Output Bird Habitat extension ...
Running Output Bird Habitat ...
and no further --- an interminable stall! ( or an endless loop?)

The problem seems to be with the transform for the 'psdi' climate variable. PlugIn.cs currently is set to ignore "PDSI" (Lines 651 - 658 are commented out).  If the these lines are uncommented in PlugIn.cs the project won't build in VS. If these lines remain commented out so that the project builds  and no lines are commented out in "output_BirdHabitat.txt" (ie psdi is active), then we get,

Loading Output Bird Habitat extension ...
Error at line 48 of file "output_BirdHabitat.txt":
  Error reading input value for Transformation: Missing value

Going to push the changes up with a pull request so you can take look. Details of the run are on the Trello board in PWL74c_QAQC&RepoStd_OutputBirdHabitat.txt

**Comment by rmscheller** [comment]
Brian,
We have taken output-bird-habitat as far as we could.  It is now biomass-library compatible.  But we can't get it to run to completion.  The example Bruce is referencing above is in the deploy\examples folder.  It is also still missing a user's guide.  If you have any great insights, we can move it forward.

**Comment by rmscheller** [comment]
Cleaned up for v8.
